version: '2'
services:
  app:
    build:
      context: jvm/
    volumes:
      - ../project/:/app
      - ../datasets/:/datasets
    environment:
      - JAR_NAME=app/target/app.jar
  maven:
    build:
      context: maven/
    volumes:
      - ../project:/app
